### ISSUE TITLE
App Distribution

### ISSUE THREAD

**Issue by MatyiFKBT** [dbond09/Grapha#1]
Ha nem akarod egyesével elküldeni mindenkinek az apk fájlt, a firebase-n keresztül tudsz ilyen "tesztprogramot" csinálni, ahova akár automatizálva is fel tudod rakni az .apk (vagy .ipa) fájlokat, és a tesztelők le tudják szedni egy külön appon keresztül + kapnak e-mailt minden release-ről. 

https://firebase.google.com/docs/app-distribution

**Comment by MatyiFKBT** [comment]
meg amúgy én is szívesen tesztelem

**Comment by dbond09** [comment]
Már fent van Google Play-en az alfa verzió, szerintem az egyszerűbb.

[https://play.google.com/apps/testing/com.dbond09.grapha](https://play.google.com/apps/testing/com.dbond09.grapha)
